=== 00willo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "description":"The schema for a video record in pytube/data",
  "properties":{
    "alias":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"A unique identifier for a particular video",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "format":"date-time",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "slug":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "source_url":{
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations",
      "items":{
        "description":"A video location",
        "properties":{
          "type":{
            "type":"string"
          },
          "url":{
            "format":"uri",
            "type":"string"
          },
          "length":{
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true
    }
  },
  "required":[
    "title",
    "speakers",
    "videos"
  ],
  "title":"Video",
  "type":"object"
}

=== 00willo/data/data/europython-2011/videos/browse-and-print-problems-and-solutions.json
{
  "id": 1006, 
  "category": "EuroPython 2011", 
  "slug": "browse-and-print-problems-and-solutions", 
  "title": "Browse and print problems and solutions", 
  "summary": "[EuroPython 2011] Jonathan Fine - 21 June 2011 in \"Track Tagliatelle\"\n\n", 
  "description": "With the growth of the web, how we publish is changing. Paper alone is not\nenough, web pages are also required. And for many web pages it is not enough\nto rely on the browser\u2019s print capabilities. Sphinx, used since 2008 for\nPython\u2019s documentation, is a creative response to this tension.\n\nThis talk will take a broader view of the problem. For example, many browsers\nsupport web fonts for display but not for printing. Mathematics on web pages\nis still difficult, but SVG holds out much promise not only for mathematics\nbut for tables and other complex typeset material. Achieving accessibility\nremains difficult.\n\nBased on over 15 year\u2019s experience in print and electronic publishing, this\ntalk will survey problems and emerging solutions. Software and sites covered\ninclude LaTeX, PDF, SVG, MathJax, web-fonts, PediaPress, Sphinx and arXiv.\n\n", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "Standard YouTube License", 
  "thumbnail_url": "http://i.ytimg.com/vi/ilwSRRLlOnE/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=ilwSRRLlOnE", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=ilwSRRLlOnE", 
  "tags": [
    "accessibility", 
    "sphinx", 
    "web"
  ], 
  "speakers": [
    "Jonathan Fine"
  ], 
  "recorded": "2012-02-27"
}

=== 00willo/data/data/pycon-de-2011/videos/ideenklau-erwunscht-konzepte-aus-der-zope-welt.json
{
  "id": 2912, 
  "category": "PyCon DE 2011", 
  "slug": "ideenklau-erwunscht-konzepte-aus-der-zope-welt", 
  "title": "Ideenklau erw\u00fcnscht: Konzepte aus der Zope-Welt", 
  "summary": "Der Applikations-Server Zope und die Bibliotheken in seinem Umfeld enthalten eine Vielzahl von Konzepten zur Entwicklung von Webanwendungen. In diesem Vortrag werden einige Ideen erl\u00e4utert, die es so in anderen Frameworks nicht gibt. Es bleibt aber nicht bei theoretischen \u00dcberlegungen, es werden Werkzeuge vorgestellt, die unabh\u00e4ngig von Zope sind und direkt eingesetzt werden k\u00f6nnen.", 
  "description": "", 
  "quality_notes": "", 
  "language": "German", 
  "copyright_text": "http://www.youtube.com/t/terms", 
  "thumbnail_url": "http://i1.ytimg.com/vi/35HkKlmPoxU/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=35HkKlmPoxU", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=35HkKlmPoxU", 
  "tags": [], 
  "speakers": [
    "Wolfgang Schnerring"
  ], 
  "recorded": "2011-10-06"
}

=== 00willo/data/pycon-india-2015/videos/sponsored-python-in-enterprise-part2-zeomega-pycon-india-2015.json
{
    "description": "Details: https://in.pycon.org/cfp/schedule_item/22/",
    "recorded": "",
    "speakers": [
        "https://in.pycon.org/cfp/schedule_item/22"
    ],
    "thumbnail_url": "https://i.ytimg.com/vi/LeuQ409r1hg/hqdefault.jpg",
    "title": "Sponsored - Python in Enterprise - Part2 - ZeOmega - PyCon India 2015",
    "videos": [
        {
            "type": "youtube",
            "url": "https://www.youtube.com/watch?v=LeuQ409r1hg"
        }
    ]
}

=== 00willo/data/pycon-us-2015/videos/what-python-can-learn-from-erlang.json
{
  "alias": "video/3414/what-python-can-learn-from-erlang",
  "category": "PyCon US 2015",
  "copyright_text": "creativeCommon",
  "description": "",
  "duration": null,
  "id": 3414,
  "language": "English",
  "quality_notes": "",
  "recorded": "2015-04-11",
  "slug": "what-python-can-learn-from-erlang",
  "source_url": "https://www.youtube.com/watch?v=EmICpC_QmhI",
  "speakers": [
    "Benoit Chesneau"
  ],
  "summary": "",
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/EmICpC_QmhI/hqdefault.jpg",
  "title": "What Python can learn from Erlang",
  "videos": [
    {
      "length": 0,
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=EmICpC_QmhI"
    }
  ]
}

=== 00willo/data/data/pycon-us-2014/videos/django-for-web-designers-and-front-end-developers.json
{
  "id": 2624,
  "category": "PyCon US 2014",
  "slug": "django-for-web-designers-and-front-end-developers",
  "title": "Django for Web Designers and Front End Developers",
  "summary": "Traditional tutorials for Django usually assume some programming\nexperience, but what if someone is learning Python and Django with a\nHTML/CSS background? This tutorial focuses on the web-based features of\nDjango \u2014 templates and the admin \u2014 and goes over the basic building\nblocks of Django programming to get web designers excited and interested\nin learning more.\n",
  "description": "",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "http://www.youtube.com/t/terms",
  "thumbnail_url": "http://i1.ytimg.com/vi/-l3ILra8ewI/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=-l3ILra8ewI",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "http://www.youtube.com/watch?v=-l3ILra8ewI",
  "tags": [],
  "speakers": [
    "David Wolever",
    "Tracy Osborn"
  ],
  "recorded": "2014-04-12"
}

=== 00willo/data/data/kiwi-pycon-2014/videos/semver-and-python-with-pbr.json
{
  "id": 3235, 
  "category": "Kiwi PyCon 2014", 
  "slug": "semver-and-python-with-pbr", 
  "title": "Semver and Python with PBR", 
  "summary": "", 
  "description": "= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = \r\nRobert Collins:\r\nSemver and Python with PBR\r\n= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = \r\n@ Kiwi PyCon 2014 - Saturday, 13 Sep 2014 - Track 1\r\nhttp://kiwi.pycon.org/\r\n\r\n**Audience level**\r\n\r\nNovice\r\n\r\n**Description**\r\n\r\nPBR is a setuptools plugin which OpenStack developed to provide simple and consistent minimal-boilerplate build definitions for its projects. Semantic versioning provides simple and robust rules for deciding on version numbers, and PBR will soon be able to manage the entire process of version number assignment in a project... and more.\r\n\r\n**Abstract**\r\n\r\nPBR is a setuptools plugin which OpenStack developed to provide simple and consistent minimal-boilerplate build definitions for its projects. Now used by all the OpenStack projects, PBR provides integration glue for core features:\r\n\r\n - testing\r\n - binary package creation for Linux distributors\r\n - inclusion of files in tarballs\r\n - changelog and authors file creation\r\n - pypi summary creation\r\n - version number creation\r\n - sphinx doc stub creation and manpage enablement\r\n - unified requirements management\r\n - for both easy-install and pip with single-file control\r\n\r\nThe most interesting part is the version number creation, since coming up with the right version number can be a contentious discussion in some projects. Semver provides simple and robust rules for deciding on version numbers, and I'm in the middle of implementing automation for these in PBR itself, with integration glue to export them in PEP-440, dpkg and rpm format. The only dependencies PBR has are git + a recent pip, so this should be useful for many attendees - and while PBR is an OpenStack invention we're very interested in making sure its useful and reliable for anyone that wants to use it.\r\n\r\n**Slides**\r\n\r\nhttps://speakerdeck.com/nzpug/robert-collins-semver-and-python-with-pbr", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "CC", 
  "thumbnail_url": "http://i.ytimg.com/vi/6hjg-Uia5AU/hqdefault.jpg", 
  "duration": 1800, 
  "videos": [
    {
      "url": "http://youtu.be/6hjg-Uia5AU", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://youtu.be/6hjg-Uia5AU", 
  "tags": [
    "talk"
  ], 
  "speakers": [
    "Robert Collins"
  ], 
  "recorded": "2014-09-13"
}

=== 00willo/data/pycon-us-2013/videos/the-naming-of-ducks-where-dynamic-types-meet-sma.json
{
  "id": 1676,
  "category": "PyCon US 2013",
  "slug": "the-naming-of-ducks-where-dynamic-types-meet-sma",
  "title": "The Naming of Ducks: Where Dynamic Types Meet Smart Conventions",
  "alias": "video/1676/the-naming-of-ducks-where-dynamic-types-meet-sma",
  "summary": "While Java and C# use static type declarations to eliminate ambiguity,\nthe Python programmer must survive through sheer clarity and consistency\nin naming variables. We will explore the deep unspoken conventions that\nthe Python community has developed and honed over two decades to make\nPython code readable and meaningful within the freedom that a\ndynamically-typed language grants us.\n",
  "description": "",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "CC",
  "thumbnail_url": "http://i.ytimg.com/vi/YklKUuDpX5c/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://s3.us.archive.org/nextdayvideo/psf/pycon2013/The_Naming_of_Ducks_Where_Dyna.mp4?Signature=drvwKQMFi5Vt2QItklKi9KnG0n8%3D&Expires=1363836226&AWSAccessKeyId=FEWGReWX3QbNk0h3",
      "type": "mp4",
      "length": null
    },
    {
      "url": "https://www.youtube.com/watch?v=YklKUuDpX5c",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "https://www.youtube.com/watch?v=YklKUuDpX5c",
  "tags": [
    "talk"
  ],
  "speakers": [
    "Brandon Rhodes"
  ],
  "recorded": "2013-03-15"
}

=== 00willo/data/data/scipy-2014/videos/pymc-markov-chain-monte-carlo-in-python.json
{
  "id": 2734, 
  "category": "SciPy 2014", 
  "slug": "pymc-markov-chain-monte-carlo-in-python", 
  "title": "PyMC: Markov Chain Monte Carlo in Python", 
  "summary": "PyMC is a Python module that implements Bayesian statistical models and fitting algorithms, including Markov chain Monte Carlo (MCMC). Its flexibility, extensibility, and clean interface make it applicable to a large suite of statistical modeling applications. The upcoming release of PyMC 3 features an expanded set of MCMC samplers, including Hamiltonian Monte Carlo.", 
  "description": "[PyMC](http://pymc-devs.github.io/pymc/) is a Python module that implements Bayesian statistical models and fitting algorithms, including Markov chain Monte Carlo (MCMC). Its flexibility and extensibility make it applicable to a large suite of problems. Along with core sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence diagnostics. PyMC seeks to make Bayesian analysis as painless as possible, so that it may be used by a range of data analysts. Its key features include:\r\n\r\n* Fits Bayesian statistical models with Markov chain Monte Carlo and other algorithms.\r\n* Includes a large suite of well-documented statistical distributions.\r\n* Uses NumPy for numerics wherever possible.\r\n* Includes a module for modeling Gaussian processes.\r\n* Sampling loops can be paused and tuned manually, or saved and restarted later.\r\n* Creates summaries including tables and plots.\r\n* Traces can be saved to the disk as plain text, Python pickles, SQLite or MySQL database, or hdf5 archives.\r\n* Several convergence diagnostics are available.\r\n* Extensible: easily incorporates custom step methods and unusual probability distributions.\r\n* MCMC loops can be embedded in larger programs, and results can be analyzed with the full power of Python.\r\n\r\nThe upcoming release of [PyMC 3](https://github.com/pymc-devs/pymc) features an expanded set of MCMC samplers, including Hamiltonian Monte Carlo. For this, we tap into the power of Theano to provide automatic evaluation of mathematical expressions, including gradients used by modern MCMC samplers.\r\n\r\nThe [source](https://github.com/pymc-devs/pymc) and [documentation](http://pymc-devs.github.io/pymc/) for PyMC can be found on GitHub.", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "http://www.youtube.com/t/terms", 
  "thumbnail_url": "http://i1.ytimg.com/vi/XbxIo7ScVzc/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=XbxIo7ScVzc", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=XbxIo7ScVzc", 
  "tags": [
    "markov", 
    "monte carlo"
  ], 
  "speakers": [
    "Chris Fonnesbeck"
  ], 
  "recorded": "2014-07-09"
}
