=== 00willo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "description":"The schema for a video record in pytube/data",
  "properties":{
    "alias":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"A unique identifier for a particular video",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "format":"date-time",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "slug":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "source_url":{
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations",
      "items":{
        "description":"A video location",
        "properties":{
          "type":{
            "type":"string"
          },
          "url":{
            "format":"uri",
            "type":"string"
          },
          "length":{
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true
    }
  },
  "required":[
    "title",
    "speakers",
    "videos"
  ],
  "title":"Video",
  "type":"object"
}

=== 00willo/data/data/pycon-us-2015/videos/django-in-depth-0.json
{
  "id": 3505, 
  "category": "PyCon US 2015", 
  "slug": "django-in-depth-0", 
  "title": "Django in Depth", 
  "summary": "", 
  "description": "This is a tutorial that goes beyond most tutorials; it's meant for developers who already know a bit about Django and want to really understand the inner guts of the framework. This tutorial will *not* involve writing code or apps; rather, it'll be a deep tour of the workings and APIs of Django itself, across all the bundled components and at all levels of the stack.\n\n", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "creativeCommon", 
  "thumbnail_url": "https://i.ytimg.com/vi/tkwZ1jG3XgA/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "https://www.youtube.com/watch?v=tkwZ1jG3XgA", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "https://www.youtube.com/watch?v=tkwZ1jG3XgA", 
  "tags": [], 
  "speakers": [
    "James Bennett"
  ], 
  "recorded": "2015-04-10"
}

=== 00willo/data/data/pycon-us-2013/videos/python-for-humans-1.json
{
  "id": 1785, 
  "category": "PyCon US 2013", 
  "slug": "python-for-humans-1", 
  "title": "Python for Humans", 
  "summary": "Python\u2019s ecosystem is held up to a high standard, but it falls short in a few key areas. A handful of crucial APIs are an absolute pain to work with. We\u2019ll go over where these APIs went wrong and learn about strong and elegant API design. The high barriers to entry in Python will be discussed. Potential solutions will be proposed. ", 
  "description": "", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "CC", 
  "thumbnail_url": "http://i2.ytimg.com/vi/QpkHt1hDYTo/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://s3.us.archive.org/nextdayvideo/psf/pycon2013/Getting_Python_and_Django_Thro.mp4?Signature=QZTC36G3tjbxEoaC9FtitPfiptw%3D&Expires=1364652846&AWSAccessKeyId=FEWGReWX3QbNk0h3", 
      "length": null, 
      "type": "mp4"
    }, 
    {
      "url": "https://www.youtube.com/watch?v=QpkHt1hDYTo", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "https://www.youtube.com/watch?v=QpkHt1hDYTo", 
  "tags": [
    "talk"
  ], 
  "speakers": [
    "Kenneth Reitz"
  ], 
  "recorded": "2013-03-16"
}

=== 00willo/data/data/scipy-2014/videos/socialite-python-intergrated-query-language-for.json
{
  "id": 2729, 
  "category": "SciPy 2014", 
  "slug": "socialite-python-intergrated-query-language-for", 
  "title": "SociaLite: Python intergrated query Language for Data Analysis", 
  "summary": "SociaLite is a Python-integrated query language for data analysis. It makes scientific data analysis simple, yet achieves fast performance with its compiler optimizations. We support relational tables and operations in SociaLite as well as Python integration, which makes it easy to implement various analysis algorithms, including Blast algorithm and genome assembly algorithm in bioinformatics.", 
  "description": "SociaLite is a Python-integrated query language for distributed data analysis.  \r\nIt makes scientific data analysis simple, yet achieves fast performance with its compiler optimizations. The performance of SociaLite is often more than three orders of magnitude faster than Hadoop programs, and close to optimized C programs.  For example, PageRank algorithm can be implemented in just 2 lines of SociaLite query, which runs nearly as fast as an optimal parallelized C code. \r\n\r\nSociaLite supports well-known high-level concepts to make data analysis easy for non-expert programmers.\r\nWe support relational tables for storing data, and relational operations, such as join, selection, and projection, for processing the data. Moreover, SociaLite queries are fully integrated with Python, so both SociaLite and Python code can be used to implement data analysis logic.  For the integration with Python, we support embedding and extending SociaLite, where embedding supports using SociaLite queries directly in Python code, and extending supports using Python functions in SociaLite queries. \r\n\r\nThe Python integration makes it easy to implement various analysis algorithms in SociaLite and Python. For example, the BLAST algorithm in bioinformatics can be implemented in just a few lines of SociaLite queries and Python code. Also genome assembly algorithm -- generating a De Bruijn graph and applying Eulerian cycle algorithm -- can be simply implemented. In the talk, I will demonstrate these algorithms in SociaLite as well as more general algorithms such as K-means clustering and logistic regression.\r\n\r\nThe SociaLite queries are compiled to highly optimized parallel/distributed code; we apply optimizations such as pipelined evaluation and prioritization. The runtime system also speeds up the performance; for example, the customized memory allocator reduces memory allocation time and footprint.  In short, SociaLite makes high-performance data analysis easy with its high-level abstractions and compiler/runtime optimizations.", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "http://www.youtube.com/t/terms", 
  "thumbnail_url": "http://i1.ytimg.com/vi/IjrK4cESxJI/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=IjrK4cESxJI", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=IjrK4cESxJI", 
  "tags": [
    "bioinformatics", 
    "blast", 
    "data analysis"
  ], 
  "speakers": [
    "Jiwon Seo"
  ], 
  "recorded": "2014-07-09"
}

=== 00willo/data/data/pycon-za-2013/videos/panel-discussion-effective-team-practices-in-sof-0.json
{
  "id": 3915, 
  "category": "PyCon ZA 2013", 
  "slug": "panel-discussion-effective-team-practices-in-sof-0", 
  "title": "Panel discussion: Effective Team Practices in Software Development (part 2)", 
  "summary": "", 
  "description": "", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "http://creativecommons.org/licenses/by/3.0/", 
  "thumbnail_url": "http://archive.org/download/pyconza2013-panel-discussion-pt2/pyconza2013-panel-discussion-pt2.thumbs/pyconza2013-panel-discussion-pt2_002130.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://archive.org/download/pyconza2013-panel-discussion-pt2/pyconza2013-panel-discussion-pt2.ogv", 
      "length": null, 
      "type": "ogv"
    }
  ], 
  "source_url": "http://archive.org/details/pyconza2013-panel-discussion-pt2", 
  "tags": [
    "pyconza", 
    "pyconza2013"
  ], 
  "speakers": [], 
  "recorded": "2013-10-03"
}

=== 00willo/data/pycon-us-2013/videos/customizing-the-django-admin-the-how-and-the-why.json
{
  "id": 1755,
  "category": "PyCon US 2013",
  "slug": "customizing-the-django-admin-the-how-and-the-why",
  "title": "Customizing the Django Admin: The How and the Why",
  "alias": "video/1755/customizing-the-django-admin-the-how-and-the-why",
  "summary": "The abstraction and the flexibility the Django admin offers is matched\nby few software, even today after half a decade of it's introduction.\nThe speaker has customized it in many ways over the years. This talk\nreminisces over how supposedly large real world problems could be solved\nwith relatively less development by leveraging the power of django admin\nand using a few techniques.\n",
  "description": "",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "CC",
  "thumbnail_url": "http://i.ytimg.com/vi/ICgMg70aV7U/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://s3.us.archive.org/nextdayvideo/psf/pycon2013/Customizing_the_Django_Admin_T.mp4?Signature=bePdKYypv64MNXR1dAraGIqRbZc%3D&Expires=1363662766&AWSAccessKeyId=FEWGReWX3QbNk0h3",
      "type": "mp4",
      "length": null
    },
    {
      "url": "https://www.youtube.com/watch?v=ICgMg70aV7U",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "https://www.youtube.com/watch?v=ICgMg70aV7U",
  "tags": [
    "talk"
  ],
  "speakers": [
    "Lakshman Prasad"
  ],
  "recorded": "2013-03-16"
}

=== 00willo/data/data/pycon-au-2011/videos/lightning-talks-sunday-and-conference-close.json
{
  "id": 977,
  "category": "PyCon AU 2011",
  "slug": "lightning-talks-sunday-and-conference-close",
  "title": "Lightning talks: Sunday and Conference Close",
  "summary": "Lightning talks Sunday.\n",
  "description": "",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "Creative Commons Attribution license",
  "thumbnail_url": "http://i.ytimg.com/vi/B7MD6-nSfrU/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=B7MD6-nSfrU",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "http://www.youtube.com/watch?v=B7MD6-nSfrU",
  "tags": [
    "conference"
  ],
  "speakers": [],
  "recorded": "2011-08-23"
}

=== 00willo/data/data/pyohio-2010/videos/pyohio-2010--wrangling-the-bits--standardizing-ho.json
{
  "id": 517,
  "category": "PyOhio 2010",
  "slug": "pyohio-2010--wrangling-the-bits--standardizing-ho",
  "title": "PyOhio 2010: Wrangling the bits, standardizing how apps get built",
  "summary": "",
  "description": "Wrangling the bits, standardizing how apps get built\n\nPresented by Rick Harding\n\nAs we moved more work to Python we had to figure out how to start,\nshare, and deploy projects in a standard way. Virtualenv, pip, and Git\nto the rescue.\n\n[Note: The talk starts at around 7:20 when the mic is working.]\n",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "Creative Commons Attribution-NonCommercial-ShareAlike 3.0",
  "thumbnail_url": "http://a.images.blip.tv/Pyohio-WranglingTheBitsStandardizingHowAppsGetBuilt608.png",
  "duration": null,
  "videos": [
    {
      "url": "http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/pyohio-2010/517_pyohio-2010-wrangling-the-bits-standardizing-how-apps-get-built.flv",
      "type": "flv",
      "length": null
    }
  ],
  "source_url": "",
  "tags": [
    "deploying",
    "fabric",
    "git",
    "pip",
    "pyohio",
    "pyohio2010",
    "virtualenv"
  ],
  "speakers": [
    "Rick Harding"
  ],
  "recorded": null
}

=== 00willo/data/pycon-us-2013/videos/pyramid-for-humans.json
{
  "id": 1664,
  "category": "PyCon US 2013",
  "slug": "pyramid-for-humans",
  "title": "Pyramid for Humans",
  "alias": "video/1664/pyramid-for-humans",
  "summary": "Pyramid has emerged as a fast, modern, lightweight web framework. This\nlively, hands-on tutorial covers a little about a lot: practical\nintroductions to the most common facilities. Fun, fast-paced, and most\ncertainly not aimed at experts.\n",
  "description": "",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "CC",
  "thumbnail_url": "http://i.ytimg.com/vi/0CP7Cv4G6x0/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://s3.us.archive.org/nextdayvideo/psf/pycon2013/Pyramid_for_Humans.mp4?Signature=4AdEu7Qqi5cwSAys7J48W8QLQ%2FA%3D&Expires=1363917984&AWSAccessKeyId=FEWGReWX3QbNk0h3",
      "type": "mp4",
      "length": null
    },
    {
      "url": "https://www.youtube.com/watch?v=0CP7Cv4G6x0",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "https://www.youtube.com/watch?v=0CP7Cv4G6x0",
  "tags": [
    "tutorial"
  ],
  "speakers": [
    "Paul Everitt"
  ],
  "recorded": "2013-03-13"
}
