=== 00willo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "description":"The schema for a video record in pytube/data",
  "properties":{
    "alias":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"A unique identifier for a particular video",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "format":"date-time",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "slug":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "source_url":{
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"",
      "items":{
        "description":"",
        "type":"string"
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations",
      "items":{
        "description":"A video location",
        "properties":{
          "type":{
            "type":"string"
          },
          "url":{
            "format":"uri",
            "type":"string"
          },
          "length":{
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true
    }
  },
  "required":[
    "title",
    "speakers",
    "videos"
  ],
  "title":"Video",
  "type":"object"
}

=== 00willo/data/pycon-ru-2016/videos/prodvinutoe-ispolzovanie-pytest.json
{
  "description": "Большинство разработчиков пишут тесты с помощью стандартной библиотеки unittest и довольны жизнью. Я тоже был из таких - пока не начал интенсивно использовать py.test.\n\nК сожалению, библиотека недостаточно популяризирована, и мы попробуем восполнить этот недостаток.\n\nВ докладе речь пойдет о написании pytest fixtures (основном инструменте расширения), добавлении конфигурационных параметров, написании plugins и прочих полезных штуках.\n",
  "duration": 2577,
  "recorded": "2016-07-03",
  "speakers": [
    "Andrew Svetlov"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/7KgihdKTWY4/hqdefault.jpg",
  "title": "Продвинутое использование py.test",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=7KgihdKTWY4"
    }
  ]
}

=== 00willo/data/data/pytexas-2014/videos/graph-databases-via-networkx.json
{
  "id": 3182, 
  "category": "PyTexas 2014", 
  "slug": "graph-databases-via-networkx", 
  "title": "Graph Databases via Networkx", 
  "summary": "", 
  "description": "Graph databases are a different way to approach your data.  I'll be talking about techniques from social network analysis to do some toy problems to get you thinking in a different direction using a library called Networkx.", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "CC-BY", 
  "thumbnail_url": "http://i.ytimg.com/vi/HCre6aYeEKc/hqdefault.jpg", 
  "duration": 1500, 
  "videos": [
    {
      "url": "http://64966d3674e0a64d8f4a-47c94b14ef8e1f83d5390cdb0629c6ed.r53.cf2.rackcdn.com/pytexas-2014/3182_Graph_Databases_via_Networkx.webm", 
      "length": null, 
      "type": "webm"
    }, 
    {
      "url": "http://youtu.be/HCre6aYeEKc", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://youtu.be/HCre6aYeEKc", 
  "tags": [], 
  "speakers": [
    "Jeremy Langley"
  ], 
  "recorded": "2014-10-04"
}

=== 00willo/data/data/pytexas-2014/videos/snakes-in-sheets.json
{
  "id": 3197, 
  "category": "PyTexas 2014", 
  "slug": "snakes-in-sheets", 
  "title": "Snakes in Sheets", 
  "summary": "", 
  "description": "Microsoft Excel continues to be popular across many industries where data analysis is fundamental to success. It marries powerful organization and presentation functionality to sift through large datasets. However, the default scripting language for Excel, VBA, is often cumbersome to use. Python is maturing as a quantitative scripting language with a growing scientific community around it, so it makes great sense to marry Excel\u2019s user interface with Python\u2019s extensive data acquisition and analysis libraries.\r\n\r\nThis talk introduces you to Pyinex, an open source project to embed a Python interpreter within an Excel addin. It directly exposes Python user defined functions as Excel worksheet functions, allows users to call arbitrary Python code from within Excel, and provides an interactive Python session all from within the same process space. Pyinex brings to Excel all the goodies of Python\u2014data analysis using SciPy, NumPy, Pandas and more; integration with databases, web services, and other network resources; rapid function prototyping; extensive library support; and so much more.\r\n\r\nThis talk will demonstrate the capabilities of Pyinex and give an overview of how it works internally.  The aim is to present the tool for both end-users and developers to inspire the audience thinking of new use cases and spark conversation on how to further improve the project.\r\n", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "CC-BY", 
  "thumbnail_url": "http://i.ytimg.com/vi/X3ImPHjAmUQ/hqdefault.jpg", 
  "duration": 3000, 
  "videos": [
    {
      "url": "http://64966d3674e0a64d8f4a-47c94b14ef8e1f83d5390cdb0629c6ed.r53.cf2.rackcdn.com/pytexas-2014/3197_Snakes_in_Sheets.mp4", 
      "length": null, 
      "type": "mp4"
    }, 
    {
      "url": "http://64966d3674e0a64d8f4a-47c94b14ef8e1f83d5390cdb0629c6ed.r53.cf2.rackcdn.com/pytexas-2014/3197_Snakes_in_Sheets.webm", 
      "length": null, 
      "type": "webm"
    }, 
    {
      "url": "http://www.youtube.com/watch?v=X3ImPHjAmUQ", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=X3ImPHjAmUQ", 
  "tags": [], 
  "speakers": [
    "Abhipray Sahoo"
  ], 
  "recorded": "2014-10-05"
}

=== 00willo/data/data/pycon-us-2012/videos/a-gentle-introduction-to-gis.json
{
  "id": 887, 
  "category": "PyCon US 2012", 
  "slug": "a-gentle-introduction-to-gis", 
  "title": "A Gentle Introduction to GIS", 
  "summary": "Datums! Coordinate systems! Map projections! Topologies! Spatial applications\nare a nebulous, daunting concept to most Pythonistas. This talk is a gentle\nintroduction into the concepts, terminology and tools to demystify the world\nof the world.\n\n", 
  "description": "", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "", 
  "thumbnail_url": "http://img.youtube.com/vi/LddeJ06JoXE/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "https://www.youtube.com/watch?v=LddeJ06JoXE", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "https://www.youtube.com/watch?v=LddeJ06JoXE", 
  "tags": [], 
  "speakers": [
    "Jason Scheirer"
  ], 
  "recorded": "2012-03-10"
}

=== 00willo/data/data/pycon-us-2014/videos/dynamics-and-control-with-python.json
{
  "id": 2653, 
  "category": "PyCon US 2014", 
  "slug": "dynamics-and-control-with-python", 
  "title": "Dynamics and Control with Python", 
  "summary": "In this tutorial we will first learn how to solve, simulate, and visualize multibody dynamics problems with Python. These methods and techniques play an important role in the design of robots, vehicles, spacecraft, manufacturing machines, etc.", 
  "description": "", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "http://www.youtube.com/t/terms", 
  "thumbnail_url": "http://i1.ytimg.com/vi/IoMR-ESzqw8/hqdefault.jpg", 
  "duration": null, 
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=IoMR-ESzqw8", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://www.youtube.com/watch?v=IoMR-ESzqw8", 
  "tags": [], 
  "speakers": [
    "Jason Moore", 
    "Tarun Gaba"
  ], 
  "recorded": "2014-04-12"
}

=== 00willo/data/data/pygotham-2015/videos/large-scale-non-linear-learning-on-a-single-cpu.json
{
  "id": 3809, 
  "category": "PyGotham 2015", 
  "slug": "large-scale-non-linear-learning-on-a-single-cpu", 
  "title": "Large scale non-linear learning on a single CPU", 
  "summary": "", 
  "description": "This talk presents several methods for learning non-linear models on a single machine, where the dataset does not fit into ram. It will cover the hashing trick, kernel approximations, neural networks, and extreme learning machines (random neural networks).\r\nThis will be a fairly technical talk, showing off some of the lesser known out-of-core capabilities of scikit-learn.", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "CC BY-SA", 
  "thumbnail_url": "https://i.ytimg.com/vi/l43VIw5xhTg/hqdefault.jpg", 
  "duration": 1519, 
  "videos": [
    {
      "url": "http://64966d3674e0a64d8f4a-47c94b14ef8e1f83d5390cdb0629c6ed.r53.cf2.rackcdn.com/pygotham-2015/3809_Large_scale_nonlinear_learning_on_a_single_CPU.mp4", 
      "length": null, 
      "type": "mp4"
    }, 
    {
      "url": "http://youtu.be/l43VIw5xhTg", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  "source_url": "http://youtu.be/l43VIw5xhTg", 
  "tags": [], 
  "speakers": [
    "Andreas Mueller"
  ], 
  "recorded": "2015-08-16"
}

=== 00willo/data/data/pycon-au-2012/videos/visualising-architecture.json
{
  "id": 1647,
  "category": "PyCon AU 2012",
  "slug": "visualising-architecture",
  "title": "Visualising architecture",
  "summary": "Architecture. It's an oxymoron all by itself, and using Python is no\nsilver bullet to the perennial problem of code rot and design\ncomplexity. How does complexity bite us in practise? What tools exist to\nsimplify and explain arc\n",
  "description": "Architecture. It's an oxymoron all by itself, and using Python is no\nsilver bullet to the perennial problem of code rot and design\ncomplexity. How does complexity bite us in practise? What tools exist to\nsimplify and explain architecture? Is anybody doing this right? This\ntalk will cover some tools that exist for visualising Python codebases,\nexamining architectures and how to deal with things in practise.\n",
  "quality_notes": "",
  "language": "English",
  "copyright_text": "http://www.youtube.com/t/terms",
  "thumbnail_url": "http://i.ytimg.com/vi/vOyF_LDeXTc/hqdefault.jpg",
  "duration": null,
  "videos": [
    {
      "url": "http://www.youtube.com/watch?v=vOyF_LDeXTc",
      "type": "youtube",
      "length": 0
    }
  ],
  "source_url": "http://www.youtube.com/watch?v=vOyF_LDeXTc",
  "tags": [],
  "speakers": [
    "Tennessee Leeuwenburg"
  ],
  "recorded": "2012-08-21"
}

=== 00willo/data/data/djangocon-eu-2010/videos/djangoconeu-seanoconnor982flv.json
{
  "id": 2475, 
  "category": "DjangoCon EU 2010", 
  "slug": "djangoconeu-seanoconnor982flv", 
  "title": "Djangoconeu-SeanOConnor982.flv", 
  "summary": "", 
  "description": "", 
  "quality_notes": "", 
  "language": "English", 
  "copyright_text": "", 
  "thumbnail_url": null, 
  "duration": null, 
  "videos": [
    {
      "url": "http://05d2db1380b6504cc981-8cbed8cf7e3a131cd8f1c3e383d10041.r93.cf2.rackcdn.com/djangocon-eu-2010/Djangoconeu-SeanOConnor982.flv", 
      "length": null, 
      "type": "flv"
    }
  ], 
  "source_url": null, 
  "tags": [], 
  "speakers": [], 
  "recorded": null
}
